source "https://rubygems.org"

ruby "3.1.0"
gem "sinatra", "~>1.4.7"
gem "sinatra-contrib"
gem "erubis"
gem "webrick"
gem "rack-test"
gem "minitest"
gem "minitest-reporters"
gem "redcarpet"
gem "bcrypt"
